spring:
  application:
    name: develop
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_HOST:192.168.31.206}:8848
        file-extension: properties
        namespace: ${NACOS_NAMESPACE:beb8479d-da1c-4132-b781-91f284836210}
        group: ${NACOS_GROUP:NX_GROUP}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        # 确保这些属性在 config.import 之前定义
        refresh-enabled: true
        shared-configs:
          - data-id: common.properties
            group: ${NACOS_GROUP:NX_GROUP}
            refresh: true
          - data-id: common_A.properties
            group: ${NACOS_GROUP:NX_GROUP}
            refresh: true
        name: ${spring.application.name}
      discovery:
        server-addr: ${NACOS_HOST:192.168.31.206}:8848
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        namespace: ${NACOS_NAMESPACE:beb8479d-da1c-4132-b781-91f284836210}
        group: ${NACOS_GROUP:NX_GROUP}

  # 关键配置 - 必须放在 cloud.nacos 后面
  config:
    import:
      - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}?group=${spring.cloud.nacos.config.group}
      - optional:nacos:common.properties?group=${spring.cloud.nacos.config.group}
      - optional:nacos:common_A.properties?group=${spring.cloud.nacos.config.group}